DATASET:
  DATA_DIR: "/homelocal/yadirapr_local/Datos/"
  NUM_CLASSES: 4
  NUM_TRAIN_IMAGES: 323
  NUM_TEST_IMAGES: 79

MODEL:
  ACTIVATION: "ReLU"
  NET_BACKBONE: "DenseNet201"
  FREEZE_BACKBONE: "False"
  SAVE_MODEL: "/homelocal/yadirapr_local/repo_modelos/Unet_3plus/modelo_prueba"
  
TRAIN:
  NUM_EPOCHES: 10
  BATCHES_PER_EPOCH: 20
  SAMPLES_PER_BATCH: 8
  EARLY_STOPPING: 3
  LEARNING_RATE: 0.0001